version: '#{build}-{branch}'
image: Visual Studio 2015

configuration: Release

environment:
  matrix:
    - PlatformToolset: v140_xp

platform:
  - x86
  - x64

build:
  project: MemView.sln
  parallel: true
  verbosity: minimal

after_build:
  cmd: >-
    7z a MemView-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\bin\MemView-%PLATFORM%.exe

    7z a MemView-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\bin\MemView-%PLATFORM%.pdb

test: off

artifacts:
  - path: MemView-$(platform).zip
    name: MemView-$(platform)

skip_commits:
  files:
    - docs/*
    - '**/*.html'

deploy:
  - provider: GitHub
    auth_token:
      secure: K/oTY+JKhuE+bOORvKuQfrFLikCqE0evsloU/50wDrtrAfsweE4aa8viM1PTkEDm
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
